### ISSUE TITLE
Minor misspelling

### ISSUE THREAD

**Issue by lepittenger** [zgordon/vanillapress#5]
Hi Zac,

I appreciate this is so minor, but I just happened to notice on line 533 in editor.js, the word update is spelled "Udpate"

Cheers and see you at WC Baltimore! :)

**Comment by JulienMelissas** [comment]
Fixed in https://github.com/zgordon/vanillapress/pull/6 😉

**Comment by zgordon** [comment]
Thanks Lauren!  And thanks Julien for fixing :)
